services:
  dynamodb-local:
    image: "amazon/dynamodb-local:latest"
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    user: root
    ports:
      - "8000:8000"
    volumes:
      - dynamodb_data:/home/dynamodblocal/data
    working_dir: /home/dynamodblocal
    networks:
      - order-demo
  backend:
    image: public.ecr.aws/sam/build-nodejs18.x
    command: "sam local start-api --container-host host.docker.internal --docker-network order-demo --host 0.0.0.0 --docker-volume-basedir ${PWD}/backend --debug"
    working_dir: /app
    volumes:
      - ./backend:/app
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "3000:3000"
    networks:
      - order-demo
  frontend:
    image: node:20
    command: sh -c "npm install && npm run dev -- --host"
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    networks:
      - order-demo


volumes:
  dynamodb_data:

networks:
  order-demo:
    name: order-demo
    driver: bridge
